<?php 
// ------------ Menu -----------------
@define ('_mangxh','Social Network');
@define ('_thongtincongty','Company Information');
@define ('_baivietkhac', 'Other Posts');
@define ('_dichvukhac','Other service');
@define ('_duankhac','Other project');
@define ('_duantieubieu','Typical projects');
@define ('_tintuckhac','Other News');
@define ('_danhmucthietke', 'Device entry');
@define ('_kientruc','Architecture');
@define ('_xaydung','Build');
@define ('_noithat','Furniture');
@define ('_banggia','Price list');
@define ('_trangchu', 'Home');
@define ('_hangmoive', 'New row');
@define ('_huongdan', 'Tutorial');
@define ('_gioithieu', 'Introduction');
@define ('_sanpham', 'Products');
@define ('_noidia', 'domestic travel');
@define ('_quocte', 'international travel');
@define ('_sanphamkhac', 'other product');
@define ('_dongphuc', 'Uniform');
@define ('_quytrinh', 'procedure');
@define ('_hoso', 'Profiles');
@define ('_tintuc', 'News');
@define ('_100', '100% natural stone');
@define ('_tintucvasukien', 'News & Events');
@define ('_khongtimthay', 'Not Found');
@define ('_duan', 'Project');
@define ('_bando', 'Map');
@define ('_khachsan', 'hotel');
@define ('_camnang', 'Travel Guide');
@define ('_doitac', 'Partner');
@define ('_tuvan', 'Consulting');
@define ('_dichvu', 'Our Services');
@define ('_tieudedichvu','Service of khôi hair');
@define ('_daily', 'Authorized Agent');
@define ('_tuyendung', 'Recruitment');
@define ('_giacong', 'Outsourcing');
@define ('_lienhe', 'contact');
@define ('_congtrinh', 'Works');
@define ('_dathang', 'Order');
@define ('_lienhevoichungtoi', 'Contact Us');
@define ('_giohang', 'Shopping Cart');
@define ('_cuahang', 'Shop');
@define ('_visaobannenchonchungtoi', 'Why should you choose us?');
@define ('_chitiet', 'Details');
@define ('_tintuchocbong', 'Learning News');
@define ('_cactruongtieubieu', 'Typical fields');
@define ('_datlich','Booking');
@define ('_dangkynhantin1', 'information will be quickly sent to you');
@define ('_chiasehocvien', 'student share');
@define ('_tinkhac', 'Other');
@define ('_binhluan', 'Comments');
@define ('_dichvuquangcao', 'Advertising Services');
@define ('_diachilienlac', 'Contact');
@define ('_gopy', 'Comment');
@define ('_khac', 'Other Products');
@define ('_tuvanthietke', 'design consultant');
@define ('_mauthietkemoi', 'New design template');
@define ('_sanphamnoibat', 'Featured Products');
@define ('_other', 'else');
@define ('_tatca', 'All');
@define ('_taikhoancuatoi', 'My Account');
@define ('_dichvusaubanhang', 'after sales service');
@define ('_tintucvasukien', 'News and Events');
@define ('_doitacchienluoc', 'Strategic Partner');
@define ('_ykienkhachhang', 'customer comments');
@define ('_danhmucsanpham', 'Product Category');
@define ('_hotrotructuyen', 'Online Support');
@define ('_sanphambanchay', 'Products Selling');
@define ('_chinhsachdaily', 'agent policy');
@define ('_chinhsachhoivien', 'membership policy');
@define ('_khampha', 'discover');
@define ('_dangky', 'Register');
@define ('_dangnhap', 'Login');
@define ('_hocbong', 'Scholarship');
@define ('_xemtatca', 'View all');
@define ('_linhhoattheodiachinguoimua', 'Flexible buyer address');
@define ('_nhanxet', 'Comments');
@define ('_chitietsanpham', 'Details');
@define ('_masanpham', 'Product code');
@define ('_muasam', 'free to buy thunder');
@define ('_dinhkemfile', 'Attach file');
@define ('_danhchokhachhang', 'For customers');
@define ('_haydelaiemaildenhanuudaituchungtoi', 'Please leave us an email to receive offers from us');
@define ('_chapnhanthanhtoanvanchuyen', 'Accept shipping payment');
@define ('_ketnoivoichungtoi', 'Connect with us');
@define ('_chunhat', 'sunday');
@define ('_phanhoigoiy', 'Suggest suggestions');
@define ('_thoigianlamviec', 'Working Time');
@define ('_tiepdienthoaingoaigio', 'Overtime Phone');
@define ('_thongtinhotro', 'Support information');
@define ('_thongtinlienhe', 'Contact Information');
@define ('_nhapemailcuaban', 'Enter your email');
@define ('_nhaptencuaban', 'Enter your name');
@define ('_nhapsodienthoai', 'Enter phone number');
@define ('_chitiet', 'see details');
@define ('_dangkynhantinhangtuan', '<span> Newsletter Subscription </ span>');
@define ('_tukhoatimkiem', 'Search keywords');
@define ('_giacu', 'Old Price');
@define ('_chamsockhachhang', 'Customer Care');
@define ('_xuatnhapkhauhoangquan', 'Hoang Quan Import & Export');
@define ('_dangkynhaptin', 'Newsletter');
@define ('_bancothethanhtoanvoi', 'You can pay with');
@define ('_trongthang', 'In month');
@define ('_maukhac', 'Other');
@define ('_thuongmai', 'Commerce');
@define ('_mauthamkhao', 'Sample Reference');
@define ('_bosuutap', 'Collector');
@define ('_dichvucamera', 'camera service');
@define ('_videosk', 'Event Video');
@define ('_lkweb', 'Link Website');
@define ('_timkiem', 'Search');
@define ('_nhaptukhoatimkiem', 'Enter search keywords.');
@define ('_thuonghieu', 'Brands');
// ---------------- Left ----------------
@define ('_muahang', 'Purchase safe');
@define ('_newproduct', 'New product');
@define ('_sanphamtieubieu', 'Featured Products');
@define ('_spchitiet', 'Product Detail');
@define ('_counter', 'Access Statistics');
@define ('_totalvisits', 'Counter:');
@define ('_chontheo', 'Choose By Brand');
@define ('_thuongkhac', 'Other Brands');
@define ('_nhapsp', 'Enter Product to Find.');
@define ('_chungkhoan', 'Securities');
@define ('_ngoaite', 'Foreign');
@define ('_hinhanhdep', 'Beautiful Image');
@define ('_ngaydang', 'Post Date');
@define ('_tinnb', 'Featured News');
@define ('_lkweb', 'Web link');
// --------------- Center ----------------

@define ('_giovn', 'images / giohang.gif');
@define ('_guiok', 'media / images / ok.gif');
@define ('_reset', 'media / images / btn_nhaplai.gif');
@define ('_photocompany', 'Company image');
@define ('_projectdetails', 'Project details');
@define ('_otherproducts', 'Other Products');
@define ('_readmore', 'more');
@define ('_newsdetail', 'Details');
@define ('_othernews', 'Other news');
@define ('_projects', 'Projects');
@define ('_contact', 'Contact');
@define ('_nhac', 'Music');
@define ('_phukien', 'Accessories');
@define ('_phongthuy', 'feng shui');
@define ('_cungdm', 'Product catalog');
@define ('_ptxemay', 'MOTOR SPARE PARTS');
@define ('_sanphamxemay', 'Motorcycle Products');
@define ('_videolienquan', 'Related videos');
// --------------- Right ----------------
@define ('_onlinesupport', 'Online Support');
@define ('_video', 'Video');
@define ('_chungchi', 'License & Certificate');
@define ('_hotro', 'Support');
@define ('_thongke', 'Statistics');
@define ('_thongketruycap', 'Access Statistics');
@define ('_quangcao', 'Advertisement');
@define ('_online', 'Online Users');
@define ('_truycap', 'Total Access');
@define ('_homnay', 'Today');
@define ('_tuannay', 'This Week');
@define ('_thangnay', 'This month');
@define ('_thang', 'Month');
@define ('_dv', 'Service');
@define ('_dssanpham', 'Product List');
@define ('_thongtin', 'Information');
@define ('_thongsp', 'Product Information');
@define ('_hinhanh', 'Image');
@define ('_danhgia', 'Product Review');
@define ('_hethong', 'HEAD SYSTEM');
@define ('_tinnb', 'NEWS UPDATED');
@define ('_sukien', 'event');
@define ('_baohanh', 'Maintenance Warranty');
@define ('_sanxuatgiacongvongdeotay', 'production of bracelets');
@define ('_mst', 'MST');
@define ('_matailieu', 'Documentation ID');
@define ('_nguon', 'Source');
@define ('_taidoan', 'Download Project');
@define ('_doanlienquan', 'related projects');
@define ('_vietnhanxetdanhgia', 'Write Review Comments');
@define ('_dangkykhoahoc', 'Course Registration');
@define ('_hocviendangkythongtinkhoahoctheomauduoiday', 'Student enrollment information in the form below');
@define ('_thongtincanhan', 'Personal Information');
@define ('_coquan', 'Agency');
@define ('_hinhthucdaotao', 'form of training');
@define ('_banvevachialuoibangphanmemgi', 'What do you draw and mesh with?');
@define ('_thoigiancothebatdauthamgiakhoahoc', 'Time can start attending the course');
@define ('_yeucaucuthe', 'Specific Request');
@define ('_ghichu1', 'Note');
@define ('_thongtinkhoahoc', 'Course Info');
@define ('_monhoc', 'Subject');

// ---------------- Footer ---------------
@define ('_thanhvien', 'Partners - Members');
@define ('_web', 'Web Design');
@define ('_address', 'Address');
@define ('_dienthoai', 'Telephone');
@define ('_tongtruycap', 'Total Counter');
@define ('_dangonline', 'Online');
@define ('_truycaptuan', 'Weekly access');
@define ('_truycapthang', 'Monthly access');
@define ('_truso', 'Headquarters');
@define ('_vanphong', 'Representative Office');

// ------------- Contact --------
@define ('_address', 'Address');
@define ('_mxn','Enter the confirmation code');
@define ('_bankhongcosanphamnaotronggiohang', 'You have no items in the cart');
@define ('_sanphamdacotronggiohang', 'Products are in the cart');
@define ('_phone', 'DT');
@define ('_mail', 'Email');
@define ('_hovaten', 'full name');
@define ('_hoten', 'Full name');
@define ('_chude', 'theme');
@define ('_noidung', 'Content');
@define ('_ghichu', 'You can contact us from this website by filling in the contact form below.We will contact you in the shortest time. sincerely thanks .. ');
// ---------------------- gio hang ------------------------ -----------

@define ('_thutu', 'order');
@define ('_tengh', 'Name');
@define ('_gia', 'Price');
@define ('_tonggia', 'Total price');
@define ('_xoa', 'Delete');
@define ('_muatiep', 'Buy next');
@define ('_xoatatca', 'Delete all');
@define ('_capnhat', 'Update');
@define ('_thanhtoan', 'payment');
@define ('_cachthucthanhtoan', 'How to pay');
@define ('_soluong', 'Quantity');
@define ('_noidungdangcapnhat', 'Content is updating');
@define ('_chuaco', 'Not yet available for this item.');
@define ('_masp', 'SP code');
@define ('_mota', 'Description');
@define ('_chon', 'Select');
@define ('_chonc', 'Select Material');
@define ('_chatlieu', 'Material');
@define ('_cantt', 'Need Payment');
@define ('_tieptuc', 'Continue');
@define ('_xemthem', 'more');
@define ('_xemtiep', 'next');
// ------------------------------------------------ -----

@define ('_chitiet', 'Product details');
@define ('_bieumau', 'size declaration');
@define ('_thongso', 'Technical Specifications');
@define ('_mausac', 'Color');
@define ('_dactrung', 'Featured Feature');
@define ('_hinhanh', 'Gallery');
@define ('_khachhang', 'Our Customers');
@define ('_trachnhiem', 'responsibility');
@define ('_danhmuc', 'Product Category');
@define ('_pt1', 'Payment method');
@define ('_pt2', 'Method');
@define ('_pt3', 'Choose payment method');
@define ('_pt4', 'Payment by cash');
@define ('_pt5', 'Money transfer by mail');
@define ('_pt6', 'ATM Transfer');
@define ('_noidungdangcapnhat', 'Content is updating');
//*********************** MOI *********************** 
@define ('_doanmau', 'Sample Project');
@define ('_daotao', 'Training');
@define ('_vieclam', 'Jobs');
@define ('_diendan', 'forum');
@define ('_thuvien', 'Library');
@define ('_tailieu', 'Document');
@define ('_baihoctructuyen', 'Online lesson');
@define ('_sukiennoibat', 'Highlights');
@define ('_timcuahang', 'Find store');
@define ('_trogiup', 'Help');
@define ('_dangkynhantinquaemail', 'Subscribe to email');
@define ('_dangkyemaildenhancacthongtinkhuyenmaimoinhat', 'Register for the latest promotion from us');
@define ('_matkinhcaocap', 'Advanced glasses');
@define ('_khuyenmai', 'Promotion');
@define ('_cungcapcacloaikinhhanghieusanhdieu', 'Provides sophisticated glasses');
@define ('_phanloai', 'Classification');
@define ('_sanphamdacbiet', 'Special Products');
@define ('_sanphamcaocap', 'Premium Products');
@define ('_sanphambinhdan', 'Popular product');
@define ('_thongtinchitiet', 'Details');
@define ('_hayguiemailcuaban', 'Please send us your email to receive the latest news from us');

@define ('_tongluottruycap', 'Total visits');
@define ('_vechungtoi', 'About us');
@define ('_chinhsach', 'Policy');
@define ('_luotxem', 'Views');
@define ('_vuilongdangnhapdexemvideodaydu', 'Please login to view our full video');
@define ('_traloi', 'reply');
@define ('_giamgiamoingay', 'Discount Daily');
@define ('_chonmausac', 'Choose color');
@define ('_trong', 'Latch');
@define ('_gong', 'Frame');
@define ('_mienphigiaohang', 'Free Shipping');
@define ('_giaohang', 'delivery service');
@define ('_thuhang', 'Try Now');
@define ('_thoigianbanhangonline', 'Online Sales Time');
@define ('_thoigianbanhang', 'Mon-Fri: 8:30 am to 5 pm Holidays and Sun: Holidays.');
@define ('_sanphamcungloai', 'Products of the same type');
@define ('_nhapemail', 'Enter email');
@define ('_stt', 'Stt');
//**************************** LOGIN ****************************** /

@define ("_tim", "Find");
@define ("_size", "size");
@define ("_gui", "send");
@define ("_nhaplai", "Re-enter");
@define ("_matkhau", "password");
@define ("_diachi", "address");
@define ("_tinmoi", "news");
@define ("_tinxemnhieu", "View more");
@define ("_guilienhe", "Send contact");
@define ("_tongtinnguoinhan", "recipient information");
@define ("_xocnhanthanhtoan", "Payment Confirmation");
@define ("_xocnhanthongtingiaohang", "Confirm delivery information");
@define ("_phuongthucthanhtoan", "Payment method");
@define ("_thanhtoankhinhanhang", "Payment upon receipt of goods");
@define ("_mienphi", "free");
@define ("_khuvuchochiminh", "Ho Chi Minh Area");
@define ("_thanhtoantaicuahang", "Payment in store");
@define ("_", "payment by bank transfer");
@define ("_thanhtoantai", "Checkout at");
@define ("_sex", "Sex");
@define ("_gioitinh", "Sex");
@define ("_", "nam");
@define ("_nu", "female");
@define ("_nhaplaimatkhau", "Retype Password");
@define ("_themsanphamvaogiohangthanhcong", "Add a product to the shopping cart successfully");
@define ("_maxacnhan", "Verification code");
@define ("_quenmatkhau", "Forgot Password");
@define ("_dangkythanhvien", "Register member");
@define ("_tieude", "title");
@define ("_guinhanxet", "Send Comments");
@define ("_doanmoicapnhat", "New Project Update");

@define ("_chucmungbandadangkythanhcong", "Congratulations on successful registration");
@define ("_xacnhantaikhoan", "Confirm account");
@define ("_camonbandadangkythanhvientren", "Thank you for registering for membership");
@define ("_detaikhoanthanhviencohieuluc", "To have a valid user account");
@define ("_emaildadangky", "Email is registered");
@define ("_neukhongphaibandadangkytaikhoan", "If you have not registered an account then please ignore this email.");
@define ("_camonbandasudungdichvucua", "Thank you for using the service of");
@define ("_moithacmachoacquantamvetaikhoan", "Any questions or concerns, please send E-mail about the account");
@define ("_luuydaychilathuthongbao", "Note: This is just a newsletter !!!");
@define ("_chucmungban", "Congratulations");
@define ("_banquenmatkhau", "Forgot password");
@define ("_chuacotaikhoan", "not have an account");
@define ("_dakichhoattaikhoanthanhcong", "account activation successful.");
@define ("_ngaytulucnayquykhachhay", "from now on you can");
@define ("_vaotaikhoan", "into your account");
@define ("_kichhoattaikhoan", "Account Activation");
@define ("_capnhattaikhoan", "Update account");
@define ("_chucmungbandacapnhattaikhoanthanhcong", "Congratulations, you have successfully updated your account.");
@define ("_capnhattaikhoankhongthanhcong", "Account update failed. Please try again.");
@define ("_coloixayrakhidangky", "There was an error registering. Please try again.");
@define ("_dangkythanhcong", "Registration Successful!");
@define ("_banchuanhapmaxacnhan", "You have not entered a confirmation code");
@define ("_maxacnhankhongchinhxac", "Incorrect verification code. Please try again.");
@define ("_chaoban", "Hello");
@define ("_exit", "exit");
@define ("_ghinho", "Remember");
@define ("_common", "certification");

@define ("_vuilongnhap", "Please enter");
@define ("_denhanlaimatkhautuchungtoi", "to receive a password from us");
@define ("_tendangnhaphoacmatkhaukhongdung", "The username or password is incorrect");
@define ("_bandadangxuatthanhcong", "You have logged out successfully");
@define ("_maxacnhankhongchinhxac", "Incorrect Verification Code");
@define ("_emaildangkydatontai", "Email registration already exists");
@define ("_chucmungbandadangnhapthanhcong", "Congratulations on successful login");
@define ("_guiykienthanhcong", "Sending comments successfully");
@define ("_thongtincanhancuaban", "Your personal information");
@define ("_thongtinchung", "General Information");
@define ("_thongtintaikhoan", "Account Information");


@define('_nuocthai','waste water');
@define('_nuocuong','drinking water');
@define('_khucongnghiep','industrial zone');
@define('_coysinh','Biomedical');
@define('_hosonangluc','Profiles');
@define('_emaillienhe','Contact Email');
@define('_hotlinetuvan','Hotline consulting');
@define ('_xemchitiet','See details');

@define ("_thongtindonhang", "Order Information");
@define ("_change password", "change password");
@define ("_dangxuat", "Logout");
@define ("_capnhattaikhoanthanhcong", "Account Update Successful");
@define ("_banphaikichhoattaikhoantruockhidangnhap", "You must activate your account before signing in");  



/**/



?>